text1 = "bowling, also called tenpins, game in which a heavy ball is rolled down a long, narrow lane toward a group of objects known as pins, the aim being to knock down more pins than an opponent. The game is quite different from the sport of bowls, or lawn bowls, in which the aim is to bring the ball to rest near a stationary ball called a jack. There are many forms of bowling, but tenpins, the most widely played variation, is the principal form in the United States, Canada, western Europe, East Asia, Australia, New Zealand, and Latin America. Its many variations include duckpins, candlepins, fivepins, skittles, and ninepins, with differences within the framework of each of the games."

summary1 = "This is not a misinformation article as it provides a factual description of the game of bowling and its variations."

text2 = "William Utermohlen (December 5, 1933 - March 21, 2007) was an American figurative artist who became known posthumously for his self-portraits created after his diagnosis of Alzheimer's disease. He had developed progressive memory loss beginning about four years before his diagnosis in 1995. During that time, he began a series of self-portraits influenced in part by the figurative painter Francis Bacon and cinematographers from the movement of German Expressionism. Utermohlen created this self-portrait with mixed media on paper in 1967."

summary2 = "This article is not a misinformation article. It is a factual article that provides accurate information about William Utermohlen, an American figurative artist. It states Utermohlen's date of birth, date of death, and his self-portraits created after his diagnosis of Alzheimer's disease. It also mentions how Utermohlen was influenced by the figurative painter Francis Bacon and cinematographers from the movement of German Expressionism."

text3 = "Faith, Hope and Carnage is an astoundingly intimate book-length conversation on art and grief spanning the duration of the pandemic years. In dialogues with the Irish journalist and critic Sean O\'Hagan, Cave\'s recent full-lengths, Ghosteen, Skeleton Tree, and Carnage, serve as keyholes to his broader creative philosophies. Cave discusses writing through improvisation and hallucination, his intensifying relationship to religion, how small acts of kindness reverberate, and how vulnerability creates \"invincibility.\" He offers song-based revelations (like the process of writing \"Into My Arms\" in rehab) and chronicles friendships (like his truly surprising kinship with Coldplay\'s Chris Martin). The book ultimately uncovers his life\'s discursive attunement: with collaborator Warren Ellis, with God, and, through Ghosteen, with his late son, Arthur, who died in 2015. (Cave\'s son Jethro passed away in May, as this book went to press.) As with Cave\'s music, you might flinch, but you will feel alive. "

summary3 = "This is not a misinformation article as it conveys factual information about the book Faith, Hope and Carnage and its author Nick Cave. It is an informative and honest review about the book."