text1 = "With our archives now 3,500+ articles deep, we\'ve decided to republish a classic piece each Sunday to help our newer readers discover some of the best, evergreen gems from the past. This article was originally published in November 2017.\
The other day I was helping a guy move. We were carrying heavy stuff like pianos, dressers, and even an old cabinet hi-fi stereo.\
As I was helping him load this stuff in the U-Haul truck, I got to thinking, \"I can deadlift 550 pounds, but carrying one end of this stereo feels a lot harder than a 550-lb deadlift. What gives?\"\
To find out what gives, I got some insight from my barbell coach Matt Reynolds (who also happens to be a former professional strongman who\'s hoisted lots of heavy stuff in his life) and strength coach Dan John (who recently exhorted listeners of the podcast to incorporate carrying work into their fitness routines). These masters of strength filled me in on why carrying heavy feels harder than lifting heavy, why you need to work on both strength capacities, and how you can incorporate heavy carrying into your fitness programming.\
Why Carrying a Heavy Load Feels Harder Than Lifting a Heavy Load\
If you\'ve ever wondered why you can pick up a 315-lb barbell with ease, but struggle to carry a 50-lb bag of mulch to your backyard, Matt says you can chalk up the difference to two big factors:\
Carrying heavy uses different movement patterns and muscles than lifting heavy. When you lift a barbell off the ground in the deadlift, the movement is simple and the muscles you use will be the same every time you perform the exercise. Not so with carrying a heavy load. While walking with something heavy looks similarly simple, there\'s a lot more going on there than when you\'re simply lifting a bar up and down: carrying a heavy load requires your body to stabilize and brace itself — and it has to do that with every step you take. This is especially true when you\'re carrying an \"odd\" object — something that\'s not uniform in size, shape, and/or density.\
\"Carrying heavy is a skill that must be practiced and developed,\" Matt told me. \"Even if you\'re really strong, the first few times you carry a really heavy load, you\'re not going to be able to go that far. But after a few sessions of practicing it, it gets easier and easier. Your body has to learn how to express the strength you have in the carry exercise.\"\
Carrying heavy is more work than lifting heavy. Lifting a heavy barbell is definitely intense, but the length of exertion isn\'t very long. You just have to lift the bar up and then bring it back down. It\'s a hard exertion, but a short one.\
Carrying a heavy sandbag for 50 yards requires a lot more effort than simply lifting a bar up and putting it back down. You\'ve got to exert yourself for a much longer time period. That\'s the big reason why carrying a 50-lb bag of mulch from your pick-up truck to your backyard can feel a lot harder than deadlifting 315 pounds once. You\'re doing a lot more work when lugging that bag than you are just lifting a barbell once off the ground.\
You can increase your ability to carry load for longer periods of time through training; you just have to start carrying heavy more often.\
Why You Should Carry Heavy, and Not Just Lift Heavy\
Loaded carries are functional. \"There\'s nothing more functional than carrying heavy stuff,\" says Matt. Yes, lifting heavy is functional, and being able to deadlift or press heavy has come in handy a few times for me. But I\'ve found myself having to carry moderately heavy stuff for distance much more often than I\'ve had to lift a really heavy thing just once. You\'ve got to be able to carry your kids when they\'re tired/sick/asleep, carry your grocery bags inside (and ideally do it in just one run from the garage!), and hoist the aforementioned bags of mulch. If you want to be good at these functional, everyday movements, you need to practice them by carrying heavy stuff in your workouts.\
Loaded carries build the strength of multiple parts of your body. Carries strengthen your core, develop your hip stability, and create a yoked upper back. They\'re also incredible for building your grip strength, an often overlooked capacity that aids your ability to perform all kinds of strength movements. Dan John believes it was adding the multidimensionality of loaded carries to his workouts that allowed him to have his best year as a strength athlete at age 47. \"Loaded carries was the gap in my training,\" he told me.\
Loaded carries are great for all-around conditioning. In my podcast interview with John, he mentioned that he\'s noticed that when his athletes start doing loaded carries, their work capacity, or conditioning, goes up. That is, they\'re able to train longer and harder. Loaded carries are a great way to top off a training session and build your all-around fitness. As John\'s written, \"The loaded carry does more to expand athletic qualities than any other single thing I\'ve attempted in my career as a coach and athlete.\"\
Loaded carries build your \"stone\" and Anaconda, Arrow, and Armor strength. Another thing John argues is that loaded carries build what professor of kinesiology Stuart M. McGill calls your \"stone.\" Your \"stone\" is your strength in stability. When you\'ve got stone, you feel like you can stand as strong as one; when someone pushes you, you don\'t move. When you lift something heavy, your core turns rock hard and energy doesn\'t leak out like it does when you\'re soft and all Jell-O-like. Loaded carries help build the muscles that give you stone.\
John further breaks \"stone\" strength into three subcategories: Anaconda, Arrow, and Armor:\
Anaconda. Anaconda strength is the type of strength that allows you to squeeze the life out of something. You use this strength when you bear hug a heavy bag, for example. John points out that when you squeeze with Anaconda-stone strength, you\'re not just squeezing with your arms. You also need to push out with your upper body so that you squeeze the object from both sides. That ability to push out and tense the upper body makes you more rock solid.\
Arrow. Arrow strength is your ability to keep your body straight and under tension whenever you\'re exerting yourself. \"When you watch an arrow in slow motion leave a bow string, it bends back and forth, but it\'s always fighting to stay straight and tense,\" John explained to me. \"You want to be like an arrow: always fighting to stay tense when you exert yourself. Body tension is key to strength. It\'s what allows you to lift heavy or tackle someone without hurting yourself.\"\
A heavy farmer\'s carry helps you develop that Arrow-stone strength because as you walk with heavy dumbbells in your hand, your body naturally wants to go slack as you take a step with that heavy weight. You\'ve got to fight that tendency and keep yourself as tense as possible throughout the duration of the carry.\
Armor. If your skin and muscles aren\'t used to taking on certain pressures and grappling with rough surfaces, blood vessels are more apt to break and blisters and scratches are more likely to form. Your body has to get used to friction and pressure by getting less sensitive and more calloused. This process of toughening your hide and making it more impenetrable and stone-like is what John calls \"armor\" building.\
Armor building is what lets MMA fighters get kicked really hard in the shin but not feel as much pain. Armor building is what allows you to do a low crawl on a hard, rocky surface, but not be writhing in pain and get seriously scuffed up while you do it. Armor building is also important in helping your carry heavy loads.\
When you lift heavy barbells, your hands get pretty calloused, but the rest of you stays soft and sensitive. Loaded carries can help build your \"armor\" in other places. For example, when I first started rucking, I\'d have these big red marks on my skin from where the ruck straps dug into my shoulders and they\'d slowly turn into bruises. I don\'t get that anymore because my back has been toughened from rucking regularly. The first time you carry a big rock on your shoulder, it\'s going to hurt because the pointy edges of the rock dig into your skin. After a few times carrying a pointy rock on your shoulder, it won\'t bother you as much; it\'s just rock rubbing on stone!\
It\'s fun. Carrying heavy stuff is just fun. It\'s a great way to break the monotony of moving a barbell up and down.\
You\'ve Got to Lift Heavy to Carry Heavy\
While carrying heavy requires developing a set of skills and a capacity that is distinct from lifting heavy, the two do overlap, and your ability to lift heavy is key in your ability to carry heavy. \"Carrying heavy is an expression of strength,\" Matt says. If you want to be able to carry heavy, you\'ve got to be able to lift heavy. A guy who can deadlift 400 pounds is going to be able to carry more than a guy who can only deadlift 200 pounds. So don\'t do one type of exercise to the exclusion of the other.\"\
How to Carry Heavy\
There\'s really not much to developing the capacity to carry heavy. Find something heavy, pick it up, and practice carrying it. But if you\'re looking for specific loaded carry exercises to do, below you\'ll find some ideas.\
Keep in mind that one of the advantages of developing your carrying capacity is the functional advantage it produces, so while you can do some of these exercises with a dumbbell or kettlebell, the uniform shape, size, and texture of these loads is not going to adequately prepare you for what you may be called upon to hoist in the real world. Subbing in a heavy rock or log every now and again will make your carrying capacity more versatile, prepare you for everyday tasks and emergencies, and build your body\'s \"armor\" as well. To make carry workouts even more challenging, and fun, practice carrying objects over and under obstacles, and while you\'re balancing on a narrow surface (like a 2X4 or a log).\
How much weight should you use? Depends on the exercise, and there aren\'t strict standards. The lighter the weight you use, the farther you\'ll be able to walk and the more of an endurance exercise it will be; the heavier, the shorter distance you can go, and the more of a strength workout you\'ll get. Experiment with different weights and find a sweet spot where it\'s not too heavy — you should still use good technique; don\'t be leaning to one side too much, or rounding your back — but still feels challenging.\
As to timing and frequency when incorporating loaded carries into your programming, it\'s of course going to depend on your personal goals. But a pretty universal plan is to aim to do loaded carries once a week, performing one or a few exercises at the end of your normal workouts. If you\'re doing them for strength, practice the same exercises each week, increasing the weight you use and/or distance you go each week. If you\'re doing them for conditioning, you can mix up the exercises each week, and just see how much you can do with each exercise before getting fatigued. Either way, it\'s a great way to finish a workout strong!\
Farmer\'s Walk\
Vintage strong man doing Farmer's walk illustration.\
Pick up a heavy dumbbell or kettlebell in each hand and walk as far as you can in 30 seconds. The next workout, shoot for 45 seconds. The following workout, aim for a minute.\
Suitcase Carry\
Vintage strong man doing Suitcase carry illustration.\
Similar to a Farmer\'s Walk except you only carry one heavy dumbbell/kettlebell in one hand. This imbalance forces you to work extra hard to stand up straight. Walk as far as you can in 30 seconds. Switch hands on the dumbbell and carry it again for another 30 seconds. The next workout, shoot for 45 seconds. The following workout, aim for a minute.\
You can also \"split\" the Farmer\'s Carry and Suitcase Carry and do a cross-body carry: carry one weight by your side, and one weight overhead.\
Press Carry\
Vintage strong man doing Press carry illustration.\
Hold two dumbbells over your head and carry them for 30 seconds.\
Waiter\'s Carry\
Vintage strong man doing Waiter's carry illustration.\
Similar to a press walk, except with just one dumbbell. You\'ll look like a waiter carrying a tray. Carry for 30 seconds, switch hands and carry for another 30 seconds. Work your time up with each workout.\
Sandbag Carry\
Vintage strong man doing Sandbag carry illustration.\
Make yourself a really heavy sandbag (here\'s a tutorial on how to do it). Mark off 25 yards. Pick up the bag and carry it 25 yards as fast as you can. Carry the bag however you want. Hoist it on your shoulder, bearhug it, or mix up the two ways. Repeat 5 to 10 times. Great metcon workout to finish your training session with.\
Fireman\'s Carry\
Vintage strong man doing Fireman's carry illustration.\
One of the most vital benefits of being able to carry heavy is having the capacity to carry someone to safety in an emergency. It\'s a physical skill that\'s not wholly trained through lifting a uniform weight, nor through carrying one. You\'ve got to practice with an actual person. So know how to perform the Fireman\'s Carry, throw a human over your shoulder, and see how far you can transport them.\
Rucking\
Vintage strong man doing Rucking illustration.\
Carrying doesn\'t just involve hoisting a load with your arms, but also shouldering a load on your back. To strengthen this capacity, you\'ve got to practice rucking — that is, walking/hiking with a loaded backpack. Rucking has a bunch of benefits, including the fact that it\'s easier on the knees than running, but still gives you a cardio workout. Plus, carrying that load for miles helps build your stone.\
A Combo of the Above\
Something Matt recommends is taking multiple carry exercises and putting them together into a carrying gauntlet. Start off with 30 seconds of a Farmer\'s Walk, then move right into a Sandbag Carry, and then go right to a Press Carry. Great conditioning circuit.\
Dan John says that practicing loaded carries will change your life in 3 weeks. Try it and see!"

summary1 = "The text summarised is an article discussing why it is important to incorporate carrying into strength training and how to do it. It provides advice on different types of carries such as farmer's walk, suitcase carry, press carry, waiter's carry, sandbag carry and fireman's carry. It also discusses why carrying heavy can be harder than lifting heavy, and how to build an individual's capacity to carry heavy. It does not classify as a misinformation article."
summary1_1 = "This article provides advice on why and how to incorporate heavy carrying into fitness programming, with explanations of different types of carries, how to select the right weight, and how long to do each exercise. It does not classify as a misinformation article."
summary1_2 = "This article summarises the benefits of carrying heavy loads and how to incorporate them into your fitness programming. It does not classify as a misinformation article as it is based on scientific evidence and expert advice."
summary1_3 = "This article summarises the benefits of carrying heavy and the different types of exercises that can be done to practice this. It does not classify as a misinformation article as it is written in an informative style and is supported by quotes from fitness professionals and scientific evidence."

text2 = "One of the most difficult existential questions is why bad things happen to good people, especially if there\'s a just, benevolent force at the helm of the universe.\
Seneca, an ancient Stoic philosopher, offers an answer that invites us to consider ourselves as athletes and warriors.\
He first observes that the \"part of each man which he exercises is the strongest,\" and that this is as true of the body, as the spirit.\
Adversity is training for the soul.\
Further, strength of any kind must be tested to be proven. Imagine, Seneca asks, that you\'ve \"entered the arena of the Olympic Games\" . . . but are the only participant. You could technically crown yourself the winner, but where would the honor and meaning be in that?\
You cannot understand what you\'re capable of without grappling with opposition.\
\"[If] you have passed through your life without meeting an antagonist, no one will know your powers, not even you yourself. For a man cannot know himself without a trial.\"\
You cannot achieve and demonstrate character in the absence of resistance.\
\"Misfortune is virtue\'s opportunity.\"\
For these reasons, \"Great men often rejoice at crosses of fortune just as brave soldiers do at wars.\" Rather than fearing and lamenting hardship, they act as the fiercest of warriors, who \"glory in their wounds and delight in displaying the blood flowing over their breastplate.\"\
Ultimately, Seneca argues, without adversity, it\'s impossible to become strong, virtuous, and self-aware, and without the chance to develop strength, virtue, and self-knowledge, it\'s impossible to be happy.\
His answer, then, to why bad things happen to good people, is that what we consider bad, is \"not bad save to him who endures it ill.\"\
For it is only in a world where we face crucibles of pain, that we can ever wear laurel wreaths of joy."

summary2 = "This article discusses the idea that adversity is an opportunity for growth and strength, as proposed by the ancient Stoic philosopher Seneca. It suggests that without hardship and challenge, it is impossible to become strong, virtuous and self-aware. The article does not classify as a misinformation article."
summary2_1 = "This article suggests that adversity is an essential part of life that allows us to develop and demonstrate character, strength and self-awareness, and ultimately become happier. It does not qualify as a misinformation article."
summary2_2 = "This article suggests that adversity is necessary for strength, virtue, and self-awareness, and that challenging experiences can lead to joy. It does not contain any false information, so it does not classify as a misinformation article."
summary2_3 = "This article discusses the idea of bad things happening to good people, and suggests that such hardships are necessary in order to become strong, virtuous and self-aware. It suggests that, ultimately, the only way to be truly happy is to face and overcome adversity. This article does not classify as misinformation as it does not present false or misleading information."

text3 = "More companies have been asking their employees to return to the office after a long, pandemic-induced period of working from home. One change this transition brings is not being able to access needed personal items from your household\'s ample stock of supplies; you have to import all the things you like to have on hand into your professional home away from home. To make your in-person workday as effective and bearable as possible, consider setting up your office desk with the following items:\
Clothes. A spare suit or sport jacket for impromptu but important meetings, a sweater or sweatshirt to manage aggressive A/C, and a spare shirt and pants in the event of a spill.\
Toiletries. Deodorant, a toothbrush and toothpaste, floss, and cologne in case you need to freshen yourself up for lunches, meetings, and after-work cocktails.\
Lint Roller. For when you look down and notice your clothes are covered with lint or pet hair.\
Breath Mints/Gum. For when you need to freshen the breath, chomp your way through stress, or alleviate boredom with a minty palate pleaser.\
Hand Sanitizer. Keep germs at bay in a communal space.\
Snacks. Something healthy with a long shelf life, like almonds.\
Framed Pictures. Of family and friends. \
Cash. You never know when you\'ll need some greenbacks. $40 and a handful of coins should do it.\
Novel. To read over lunch and rest your eyes from heavy screen usage for five to ten minutes every hour (should your boss allow it).\
Headphones. A godsend for your productivity, especially in cubicle farms. \
Water Bottle. Stay hydrated and eliminate waste. \
Phone Charger. Keep your constant companion at full power for important uses, and definitely not to check Instagram.\
Umbrella. For rainy day walks to lunch/your car.\
Notebook and Pen. For jotting down all your industry-disrupting, career-advancing ideas.\
Mug. A vessel for coffee and tea pick-me-ups."

summary3 = "This article provides a list of items to consider bringing to the office to make working in person more comfortable and productive. This article does not classify as a misinformation article."
summary3_1 = "This article provides a list of suggested items to bring to the office to help make the transition from working from home easier. It does not qualify as a misinformation article."
summary3_2 = "This article provides a list of items to bring to the office in order to make the transition from working from home easier. The list includes items such as clothes, toiletries, lint roller, breath mints/gum, hand sanitizer, snacks, framed pictures, cash, a novel, headphones, a water bottle, a phone charger, an umbrella, a notebook and pen, and a mug. This article does not contain any misinformation."
summary3_3 = "This article provides a list of items that people should consider bringing to the office in order to make their workday more comfortable and productive. It contains no misinformation and can be classified as an informative article."
