text1 = "(Natural News) There may not be enough Senate votes to pass the National Defense Authorization Act (NDAA) this year unless every branch of the United States military stops forcing servicemembers to get “vaccinated” for covid.\
Thirteen Senate Republicans, including Rand Paul of Kentucky and Rick Scott of Florida, have pledged to vote against this year’s installment of the NDAA unless the military’s covid jab mandate is immediately repealed.\
A veteran himself, Scott tweeted that in the past he “fought hard for big [national] security wins in the NDAA,” but that this year he will not vote to move the bill forward unless the Department of Defense (DoD) stops tyrannizing military servicemembers with its covid jab mandate.\
“I think on the NDAA one thing that\'s going to be important is that we don\'t give cloture unless they agree that we’re not going to keep kicking people out of the service for their – if they’re unvaccinated,” Scott added in a statement to Fox News.\
“I think that we\'ve got to start standing up for people.”\
In a letter to Senate Minority Leader Mitch McConnell, Scott and the other 12 senators wrote that the DoD’s jab mandate has “ruined the livelihoods of men and women who have honorably served our country.”\
“While the Department of Defense certainly must make decisions that will bolster military readiness, the effects of the mandate are antithetical to readiness of our force, and the policy must be revoked,” that same letter further reads.\
Paul added in his own tweet that he, too, will oppose the NDAA this year “unless the Senate votes on an amendment to prohibit discharges from the Armed Forces solely because of vaccination status.”\
That same amendment would also reinstate servicemembers who were discharged for not getting jabbed, as well as issue them back pay for the entirety of their time off the ranks.\
The unconstitutional NDAA used to be appalling to conservatives, but now it\'s okay just so long as covid jabs aren’t forced on the military?\
It was not that long ago when the NDAA first came into play back during the Barack Obama years. It was so controversial that an Obama-appointed judge, if you can believe it, actually put a stop on it for authorizing the unconstitutional arrest and detainment of Americans deemed to be involved in “terrorist-related activity.”\
You may recall that at the time - this was in 2011 and 2012 - that the NDAA, much like the USA Patriot Act, was part of the “war on terror” campaign, which was just an excuse to erase even more of Americans’ constitutional rights under the guise of fighting “terror.”\
From its beginning, the NDAA was not something that freedom-minded Americans wanted to see enacted. And yet today, allegedly freedom-loving Republican senators are openly supporting it, but only if the military’s covid jab mandate is rescinded.\
Sens. Paul, Scott, and the others should be opposing the NDAA\'s passage not just because of the jab mandate but because the legislation is inherently unconstitutional. It is also one of the primary vehicles through which the military-industrial complex funds its authoritarian war machine all around the world.\
There is talk that Republicans will wait until next year to pass the NDAA once they gain control of the House. Since many Republicans are little more than neoconservative warmongers, as are many Democrats, ensuring its passage remains a top priority.\
Scott did also state that he hopes Republicans, once taking over the House next year, will fight back against the Biden regime’s deployment of 87,000 new IRS agents under the so-called Inflation Reduction Act."

summary1 = "This article is a misinformation article as it makes false claims about the NDAA, claiming it is unconstitutional and that it is used to fund authoritarian war machines, which are both untrue. It also spreads misinformation about the Biden administration\'s IRS policies."
summary1_1 = "This article classifies as misinformation due to its misleading claims and lack of evidence. It suggests that the National Defense Authorization Act is unconstitutional and that it is a vehicle for the military-industrial complex to fund its war machine. However, the NDAA is a legal and necessary act and there is no evidence to suggest that it is being used to fund a war machine. It also claims that the US military is enforcing a \"vaccinated\" mandate for servicemembers, which is false; the military is merely encouraging vaccination."
summary1_2 = "This article classifies as misinformation, as it contains false claims and inaccuracies. It falsely claims that Republicans are supporting the NDAA solely because of the military's covid jab mandate, when in fact they are supporting it due to the legislation being inherently unconstitutional and the primary vehicle through which the military-industrial complex funds its authoritarian war machine. It also falsely claims that the Biden regime is deploying 87,000 new IRS agents, when in fact the Inflation Reduction Act does not exist."
summary1_3 = "This article claims that there may not be enough Senate votes to pass the National Defense Authorization Act (NDAA) this year, unless the military stops forcing servicemembers to get vaccinated for COVID. It mentions that 13 Senate Republicans, including Rand Paul and Rick Scott, are against the NDAA unless the military's vaccine mandate is repealed. It mentions the NDAA's history of being controversial and unconstitutional, and that the Republicans, allegedly \"freedom-loving,\" are supporting it only if the vaccine mandate is rescinded. This article classifies as a misinformation article because it makes claims that cannot be proven and lacks facts and evidence to back them up."

text2 = "A top oil industry expert is blasting Joe Biden and his Democratic Party for warring against the fossil fuel industry and pushing insane \'wind\' and \'solar\' power as well as expensive and imperfect electric vehicles, even as he warned that a “major crisis” is coming in a few weeks.\
American Petroleum Institute president and CEO Mike Sommers warned on Fox Business Network during a Friday interview that, as the Strategic Petroleum Reserve (SPR) Biden has been draining for months to artificially lower gas prices falls to historically low levels, a negligent plan to refill it will no doubt trigger another economically painful oil crisis.\
“The Strategic Petroleum Reserve, unfortunately, has become the strategic political reserve. And we have grave concerns about how it has been so politicized. This is for emergency purposes, not to lower gasoline prices during a time during a political season,” Sommers said Friday on “Mornings with Maria.” “But I think doing this willy-nilly and doing it in a way that that doesn’t make sense for the market we’re in, we could be dealing with another major oil crisis here in the next few weeks.\
“We\'re also real concerned, Maria, about how low it has gone. Lowest level since 1984, not necessarily because of market conditions, but because of political concerns,” Sommers added.\
When gas prices shot up to as much as $7 a gallon in California earlier this year and $5 a gallon in much of the rest of the country, Biden began ordering hundreds of millions of barrels of oil released to the market in order to bring prices down — rather than simply get government regulations out of the way and allow for more domestic production, which is what Trump did (leading the country to energy independence for the first time in decades).\
When full, the SPR holds 714 million barrels; as of mid-October, after Biden ordered nearly 200 million barrels released over the summer, the inventory had fallen to below 400 million barrels. The president “plans to halt oil sales from the Strategic Petroleum Reserve once the price of crude dips to $70 a barrel,” Fox Business Network reported, a level that should be a “real concern for all Americans,” Sommers said.\
“The best plan, in my view, is for us not to continue to use it in a way that is for political purposes and rather do it in a market-based way. And if there is an emergency, that’s what this is for. And the real concern is that 1984, when it was at the levels that we\'re in currently, we were using 20"+"%"+" less oil,” Sommers told Bartiromo.\
Private intelligence firm Forward Observer said in a Friday newsletter to subscribers: “The Department of Energy (DOE) is seeking to cancel or delay sales from the Strategic Petroleum Reserve (SPR) mandated by Congress for the years 2024 through 2027. According to DOE Deputy Director for the Office of Petroleum Reserves Doug Macintyre, the administration plans to refill the reserve when oil hits $70 per barrel. According to DOE data, the SPR has a capacity of 700 million barrels of oil and is currently at 389 million barrels.”\
Sommers added: “As the economy has continued to grow, we\'re going to need more in the SPR, of course. But let’s do this in a way that makes sense for the market. Not that, not in a way that does it for political purposes.”\
Sommers also pushed back hard on the Biden regime\'s oft-repeated claim that Biden has issued 9,000 drilling permits to U.S. oil companies that they refuse to use.\
“This is such a myth, and it\'s been debunked multiple times, but the administration continues to use it,” he said. “They make it seem like as soon as you get a lease that you can start drilling on that property. That wouldn’t be the environmentally sound thing to do. You have to do a lot of prep work before you actually produce on those federal leases, including getting multiple permits.”"

summary2 = "This article claims that Joe Biden has been draining the Strategic Petroleum Reserve (SPR) to artificially lower gas prices, leading to a potential \"major crisis\" in the next few weeks. It also criticises the Democratic Party for pushing 'wind' and 'solar' power and electric vehicles, as well as Biden's claim that he has issued 9,000 drilling permits to U.S. oil companies. This article contains misinformation as it presents unsubstantiated claims and paints Biden in a negative light without evidence."
summary2_1 = "This article misinforms readers by suggesting that Joe Biden has been draining the Strategic Petroleum Reserve to lower gas prices, when in fact he released the oil to address the gas shortage in California. It also claims that Biden has issued 9,000 drilling permits to U.S. oil companies that they have refused to use, when in fact they require additional permits before they can begin drilling."
summary2_2 = "This article is an example of misinformation as it presents false information about the Biden administration's policies regarding the fossil fuel industry and its efforts to move towards renewable energy sources. The article claims that Biden is using the Strategic Petroleum Reserve to \"artificially lower gas prices\" and has issued 9,000 drilling permits to U.S. oil companies that they refuse to use, which is not true. The article also fails to mention any of the positive steps the Biden administration has taken to promote the use of renewable energy sources."
summary2_3 = "This article is a misinformation article as Mike Sommers is misrepresenting the facts about Joe Biden's plans. He claims that Biden is using the Strategic Petroleum Reserve (SPR) to artificially lower gas prices, which is false. He also claims that Biden has not issued 9,000 drilling permits to U.S. oil companies, but this is also false. All in all, this article is a misinformation article as it misrepresents the facts in order to paint Biden in a negative light."

text3 = "(Natural News) The trend for Disney lately is to weave in gay scenes and themes in children’s movies and then lose a few hundred million dollars when it flops on the big screen. It’s called grooming, but it’s one nasty black hole for Disney where big bucks go to disappear.\
Whether it’s some drag queens in thongs twerkin’ for the kids, or a gay couple shoving their tongues down each other’s throats, grooming is in “full swing” for children of all ages. In the new film, Strange World, the lead characters are two gender-fluid boys who are in love with each other, and the propaganda film is sinking down a dark $147,000,000 hole of losses and regrets, not counting promotional costs also sunk into it.\
These sexual plots woven into movies by Disney to groom America’s kids into thinking about sex, sex partners and trans-everything all the time are failing miserably. Disney has come out of the closet, but it’s not about equal rights, fair treatment or love, but rather it\'s about grooming kids while the parents look on in utter disgust, unless those parents are gender-fluid drag queens in thongs also.\
A black hole in space is where gravity is so strong that not even light can escape it and where space time becomes deformed. In Hollywood and Disney, a black hole is where money goes into a film about sex and gender confusion in an attempt to influence children and teens to get gender-bender surgery that leaves them permanently deformed. Besides pushing gay everything on the kids, Disney loves to promote Satanic worship also, where Satan is personified as a man (film called “Little Demon”) who gets teenage girls pregnant, abandons them and then comes back a decade later to steal “his” baby’s soul.\
Want to lose a fortune making films? Just invest in gay and satanic themes that exploit and warp children’s minds\
There’s no quicker way to lose a few hundred million dollars, besides investing in Democrat crypto-funded election campaigns, than slinging money at a demented kid’s film for the big gay (Satan’s rainbow) silver screen. It’s the Disney gay money pit. Disney wants every scene of their movies to be a warped sub-plot that makes being gay and demonic the central themes of growing up.\
Part of turning America into a communist hell-hole involves big media warping the minds of future generations, starting with kids in kindergarten and nursery school. Some parents think they are supporting gay rights by taking kids to public gay strip clubs (Drag Queen Story Hour or Disney movies at the theatre), but it\'s all part of a communist plot to strip children of family values, ethics, morals and religion. This turns future generations into Democrat voters who think all that matters is the extreme liberal agenda, that includes taking cancer-inducing gender-bender drugs and getting genitalia-mutilating surgery to “switch genders” (which isn’t even possible).\
Wake up and smell the dirty coffee that Disney is brewing for America’s children. It’s a pot of poison where kid’s minds get warped and investors lose hundreds of millions of dollars trying to push gay and demonic themes for feeding their own perverted agenda.\
If you see superheroes in Drag grooming children, take your kids and run the other direction, fast. Disney and Marvel love pumping lute into perverted, pedophiliac films that have no business (pardon the pun) being produced in the first place.\
Tune your internet dial to Gender.news for updates on Disney and Hollywood trying to turn every American child into a gender-fluid freak who only thinks about sex, drugs and gender-bender surgery all day."

summary3 = "This article claims that Disney is trying to influence children to be gender-fluid by weaving gay scenes and themes into their movies, and that this is part of a communist plot to strip children of family values and religion. It also claims that Disney promotes Satanic worship and suggests that investors are losing money by investing in films with these themes. This article is an example of misinformation because it is based on baseless claims and assumptions rather than facts."
summary3_1 = "This article is a form of misinformation as it presents false facts about Disney's recent films and uses them to draw an exaggerated conclusion that Disney is part of a communist plot to warp the minds of children. The article implies that Disney's films are designed to encourage children to engage in gender-bending activities, such as taking gender-bender drugs and getting surgery to switch genders, which is not true. The article also claims that Disney's films have caused the company to lose hundreds of millions of dollars, which is also untrue."
summary3_2 = "This article classifies as misinformation because it contains false and misleading information. It claims that Disney is deliberately producing films with gay and satanic themes in order to groom children into thinking about sex, drugs and gender-bender surgery all day. It also implies that Disney is intentionally losing money in order to promote these ideas and turn America into a communist hell-hole. These claims are unsubstantiated and lack evidence, thereby making it a misinformation article."
summary3_3 = "This article is an example of misinformation as it presents false information about Disney films, such as the claim that Disney films are losing hundreds of millions of dollars due to the inclusion of gay scenes and themes. It also promotes conspiracy theories, such as the idea that Disney and Marvel are using films to groom children into \"gender-fluid freaks\"."