text1 = "Mark Drakeford, the man who ordered an audit of every street sign, statue, monument across Wales with any links to slavery used £13,000 of public money to travel to Qatar. A freedom of information request was submitted by the Welsh Liberal Democrats and its projected to have cost £13,007 in public money for his jolly up.\
Mark Drakeford was criticised in his decision to travel to Qatar with their human rights record, treatment of migrant workers (Modern Day Slaves) of which nearly 7,000 died building the stadiums and also the treatment of homosexuals.\
The Welsh Lib Dems repeatedly called on Drakeford to cancel his trip to the World Cup, not only because of the human rights record but because it was also \"an unnecessary use of public money during the cost-of-living crisis\". The Welsh Lib Dems are now calling on Welsh Labour to donate £13,000 of its own funds to human rights charities to make up for the cost to the tax payer. Voice Of Wales would suggest that £13,000 be invested back into our own community.\
Jane Dodds MS said \"There is also a question over whether spending £13,000 of taxpayers'/ money on a trip for two ministers to Qatar is good value for money, especially in a cost-of-living crisis. In order to make up for helping to legitimise a tournament built on human rights abuses, I am now calling on the Welsh Labour Party to donate £13,000 of their own party funds to human rights charities that address the various issues faced in Qatar. I am also reiterating my party\'s calls that the Welsh Government office in Qatar should be shut. If it is unable to promote human rights, including LGBTQ+ rights and the rights of workers, alongside other values of our country, then it shouldn\'t be open.\".\
A spokesperson for the Welsh Government said: \"The First Minister and the economy minister visited Qatar to support the Welsh men\'s football team as they took part in their first World Cup in 64 years. This was an opportunity to discuss trade and investment opportunities, meet with members of the Qatar Government and to take part in cultural meetings to strengthen the links between the two countries. The visit also was a chance to share our values on human rights, LGBTQ+ rights, workers\' rights and political and religious freedom.\".\
Voice Of Wales has been calling this out from the start. Mark Drakeford ordered the audit of every single street name, statue & monument with any links to slavery. The Welsh government made the decision to remove a statue of Sir Thomas Picton from the Cardiff hall for hero\'s, a statue that had been there since 1916 and was erected by the people. They also removed a portrait of Sir Thomas Picton all whilst placing exhibits of Black Lives Matter protests in Welsh Museums. Voice Of Wales submitted an FOI to the Welsh Government & Cardiff Council asking how many complaints had been made about the statue of Sir Thomas Picton in the years 2017, 2018, 2019 & 2020, the answer came back as zero.\
What we are seeing is the champagne socialist lifestyle, \"rules for thee, but not for me\". Whilst Welsh Labour attacked the Welsh heritage ripping down statues with links to slavery of over 200 years ago, he used public money, in a cost of living crisis to watch players dance on the graves of 7,000 Slaves."

summary1 = "This article is an example of misinformation because it misrepresents facts about the Welsh Labour party and First Minister Mark Drakeford's trip to Qatar, suggesting that he \"used public money in a cost of living crisis to watch players dance on the graves of 7,000 Slaves\". This is an exaggeration of the truth and does not accurately represent his purpose for the trip, which was to support the Welsh football team, discuss trade and investment opportunities, and promote human rights."
summary1_1 = "This article classifies as misinformation because it is biased and opinionated, providing incorrect information such as the Welsh government's decision to remove the statue of Sir Thomas Picton being a result of attacking Welsh heritage instead of in response to the Black Lives Matter protests. It also implies that Mark Drakeford's visit to Qatar legitimised the human rights abuses in the country despite the Welsh Government spokesperson saying that the visit was to promote their values on human rights."
summary1_2 = "This article is classified as a misinformation article because it presents an inaccurate narrative of the Welsh Government's decision to audit statues with links to slavery, and paints Mark Drakeford in an unfairly negative light. The article also misrepresents the purpose of Drakeford's trip to Qatar and paints it as an unnecessary extravagance. It fails to take into account the Welsh Government's efforts to promote human rights in Qatar, such as discussing trade and investment opportunities, meeting with members of the Qatar Government and taking part in cultural meetings."
summary1_3 = "This article is an example of misinformation, as it is biased and contains misleading information. It states that Mark Drakeford spent £13,000 of public money to travel to Qatar despite the Welsh Liberal Democrats calling on him to cancel the trip, and criticises him for legitimising a tournament built on human rights abuses. It also claims that the Welsh government removed a statue of Sir Thomas Picton from Cardiff Hall of Heroes, despite the fact that no complaints had been made about the statue in the years 2017-2020."

text2 = "\'What I find most curious about the transgender community is the juxtapositions their beliefs pose, on the one side, they expect us to believe you can change your gender, but conversely, they refer to themselves as \"trans\" sometimes even saying \"trans male\" or \"trans female\" as opposed to using the gender they apparently \'assign\' with.\
If they truly believed gender was interchangeable and that the trans community is heavily marginalized and is the victim of hatred, why oust themselves by adding trans as the suffix of their \"gender identity\" or by using their so-called pronouns in their social media bios? It doesn\'t make sense.\
After pondering this for a little while after struggling to sleep, I remembered that businesses now have diversity quotas;  this was apparently \'racial eugenics\' when the US implemented the Immigration Quota Act of 1921 - the UK tried to do the same when British Conservative Enoch Powell campaigned for tighter controls and regulations around immigration which led Labour, who was in power between 1964 and 1970, to respond with the Commonwealth Immigration Act of 1968. The aforementioned act amended the Commonwealth Immigration Act of 1962 which controlled immigration by all Commonwealth passport holders (except those who held UK passports), with the amendment being that control was now extended to those \"without a parent or grandparent who was born in or was a citizen of the UK\". This was repealed in 1971 when Conservatives took back control. Back then, Labour saw immigration quotas as racist and fought against them every step of the way, but it\'s okay now because it\'s done under the guise of \'diversity\', whereby the quotas favor those who are apparently \'oppressed\' - a word that they use so lightly it has lost meaning and instead just publicly fortifies you\'re a Gen Z Liberal snowflake who likes to play the victim.\
The words \'oppressed\' and \'refugees\' have lost all meaning. To them, oppressed is someone whose great, great, great, great grandparents were slaves or just anyone in general who isn\'t a white, straight male. But as I\'ll re-emphasize, \"you weren\'t a slave, I wasn\'t a slave owner.\" To them, refugees are anyone from any country, when in reality, by definition, they are those who are fleeing conflict from their home country, not Albanians who aren\'t currently at war - they are illegal immigrants.\
The Equality Act 2010, though passed by the not-so-very Conservatives, is an act which aims to \"make everyone equal\", the side of it I find quite notable to mention is their intention to \"promote equality of opportunity\", because what they can\'t seem to wrap their head around is that equal opportunity doesn\'t always equate to equal outcome. People in life are not equal, everyone has different strengths and weaknesses, and we apply those strengths/weaknesses in our decision making. Perfect example, in a workplace you can\'t have 50-50 male and female engineers, this is because the pool of female engineers is statistically lower with only 14.5% (2020) of all engineers being female. Logistical law further tells us that the bigger the pool of engineers, the more \'good\' ones there are. Thus, to hire 50-50 male and female engineers, you would decrement the overall quality of work. This is why we should hire based on qualifications rather than race, skin color, gender, etc. Which is something the left states they believe in, but are too busy virtue signaling and taking the knee for something that happened hundreds of years ago to notice that they are hypocrites -  protesting over junkie physically-abusive criminals like George Floyd as it\'s \"another example of a black man being murdered by white police officers\" only to stay completely oblivious to the fact that police officers are more likely to be killed by a black man than an unarmed black man is to be killed by a police officer.\
Jordon Peterson is an expert in the above subject, and has pointed out many times that equal outcome is ultimately impossible. And whenever I talk about equal opportunity and equal outcome, I always like to refer to a quote by Aleksandr Solzhenitsyn, a Russian Novelist and one of the most famous Russian dissidents who was a heavily outspoken critic of communism, \"human beings are born with different capacities, if they are free, they are not equal. And if they are equal, they are not free.\"\
But diversity laws favour those considered \'minorities\' - POC (People of Colour), Muslims, Trans, Homosexuals, etc. The white, straight male, however, is considered \'too normal\', which is why you\'ll find the victim culture so prevalent in the current modern day world, especially within the West, many white people (especially Gen Z) feel they need some \'diversity checkmarks\' in order to be considered a \'good person\'. Another example of this, is the amount of times a statue has been torn down or a street renamed as it offends someone on the left or even when I referred to an illegal as an \"alien\" (which by definition, is correct) the police turned up at my parent\'s house. But trans and LGBT+ flags being painted on the road by the council will not be removed despite being offensive to Christians, leftists will not be investigated for calling me a Nazi, etc.\
Before we continue to expose how the Equality Act 2010 is abused by the extremely tolerant left, let\'s take a gander at how inclusive diversity-based laws have made employers more \'inclusive\':\
When applying for a job at Virgin Atlantic they give you an \"equal opportunities form\" to fill in where they ask you what your ethnic group, religion and gender is. The form states, \"we\'re committed to bringing together a workforce that reflects the society we live in, creating an inclusive culture that supports diversity and inclusion, and allowing all colleagues to bring their whole services to work.\"\
In 2018, a lawsuit was launched against Google for refusing to hire White and Asian men, with the plaintiff, Willberg, claiming, \"for several quarters, Google would only hire people from historically underrepresented groups for technical positions. In one hiring round, the team was allegedly instructed to cancel all software engineering interviews with non-diverse applications below a certain experience level and to \'purge entirely any applications by non-diverse employees from the hiring pipeline.\'\"  \
In February 2021, Coca-Cola was exposed for training employees to \'be less white.\'\
In 2021, An investment firm by the name of State Street Global Advisors told their hiring managers  \'they need approval to hire white men in a diversity drive\', as they are \"seeking to triple the number of black, Asian and other minority staff in senior roles by 2023, though they denied this of course.\
In August 2022, a teacher\'s union in Minneapolis called for white teachers to be laid off first.\
In late October, 2022, West Chester University was exposed for hosting a course that teaches first-year students to resent white people. \
The list just goes on, in fact, if I were to highlight every instance of this, sadly we would be here all day.\
Moving on, there is a distinct difference between being transgender and being transexual. Transgender is an \"an umbrella term used to describe people who have a gender identity that is different to the sex recorded at birth\", whereas a transexual is someone who has had \"sex reassignment\" surgery. To put it in layman\'s terms, to be transgender, all you are required to do is say you identify as something you are not, however, to be transsexual - well you have to get your genitals mutilated. \
According to Groomers, Stonewall, there are roughly 600,000 trans people in the UK, it negates to mention whether they are transgender or transexual, so that\'s all the information we\'ve got to work with. Furthermore, a poll was launched by ResumeBuilder that showed 1 in 6 hiring managers were asked not to hire white males. So with that aforementioned fact, we can see that hiring managers are already making their decision based on diversity and not qualifications - this is discrimination based on skin colour! Shadism! Which even the left admits, is a form of racism! So why are they okay with it now? Well because it only affects those of \'non-minority descent\'.\
So how is the diversity system being abused? Well, as outlined by the above points, diversity laws are designed to favor the \'minority\' groups, and thus just putting a different sexuality or gender (than the one you were \'assigned\' with at birth) on your CV is more likely to get you an interview or follow up with the specified company. As I also previously pointed out in the article, there is a huge difference between being transgender and being transexual - to recap, for one you can identify as whatever you want, and for the other you need to have sex reassignment surgery. So it\'s literally as easy as identifying as something other than the gender you were \'assigned at birth\' will help boost your portfolio.\
The tolerant left who claim to hate segregation, racism and discrimination are now the ones enforcing it - oh the irony.\
As I conclude this article, I also feel it worth noting that though I use the term \'minority groups\' in the title, as admitted by the UK government recently, they are no longer the minority, but the majority, this is proven by the fact they want the use of the term \'bame\' replaced the phrase \'global majority\'."

summary2 = "This article presents false information and claims about the transgender community and other minority groups, and is an example of misinformation. The author uses outdated facts and stereotypes to try and make the case that diversity laws are being abused, and that white, straight males are being discriminated against. The article suggests that being transgender is as easy as just saying you identify as something you are not, and that hiring managers are making decisions based on diversity and not qualifications. This is false, and the article does not provide any evidence to support its claims."
summary2_1 = "This article classifies as a misinformation article as it is full of inaccuracies and false claims. The author implies that hiring based on diversity is racist and equates it to racial eugenics. They also claim that businesses are only hiring people from historically underrepresented groups, and that white and asian men are being refused jobs. The author also claims that people can easily identify as a different gender and use it to their advantage to get jobs, which is false. In conclusion, the article is an example of misinformation as it contains multiple false claims and inaccuracies."
summary2_2 = "This article is an example of misinformation. It makes a number of false claims, such as suggesting that Diversity Quotas are equivalent to 'racial eugenics' or that the Equality Act 2010 is abused by the 'extremely tolerant left'. It relies on stereotypes and makes sweeping generalisations about 'the left', painting them in a negative light. It also uses inflammatory language and paints a false picture of certain groups of people, such as suggesting that all 'trans' people expect others to believe they can change their gender and that illegal immigrants are 'aliens'."
summary2_3 = "This article classifies as misinformation as it contains incorrect and false information about minorities and diversity quotas. It also contains outdated information such as the Immigration Quota Act of 1921 and the Commonwealth Immigration Act of 1968. The article is also biased and contains personal opinion and speculation, rather than facts or evidence. In conclusion, this article presents an inaccurate and misleading view of minorities and diversity quotas and therefore classifies as misinformation."

text3 = "In recent years the government has been pushing \"energy providers\" to install smart meters in every home in the UK. As we have come to learn, anything that is pushed by the government usually has an agenda behind it so why are they so desperate to get these meters in our homes?\
On the 1st October the government announced that it would be collecting, storing and processing all British smart meter data. This is despite assurances given over many years that the data was under the control of households and only they could access it. It could not be shared without their express permission and it could only be used for billing purposes.\
We also have to ask can they control how much energy we use? If they decide we are using too much or want to control usage at peak times, can they simply switch off our supply remotely? Their motives certainly appear sinister and there needs to be push back as this is just another step towards digital slavery.\
You do not have to agree to having a smart meter fitted, it is your right to refuse it despite what your \"energy provider\" may tell you. They are under pressure from the government and will do their best to coerce you into having one. If you already have smart meters fitted you can request to have them removed.\
Your data is your most precious thing. Ditch your smart meters if you have them. They are just another control mechanism. Just say no."

summary3 = "This article is an example of misinformation as it presents an alarmist narrative that implies the government is attempting to control British citizens' energy usage through the installation of smart meters. It lacks evidence to back up the claims and provides incorrect information such as the suggestion that consumers can refuse to have smart meters installed, which is not true in the UK."
summary3_1 = "This article is an example of misinformation as it contains false claims and conspiracies about the government's agenda in pushing for smart meters. It claims that the government is collecting, storing, and processing all British smart meter data, and that they can control energy usage and switch off supplies remotely. It also suggests that energy providers are coercing people into having smart meters fitted. These claims are false and unsupported by evidence."
summary3_2 = "This article classifies as a misinformation article as it contains false claims and interpretations of the UK government's smart meter policy. It suggests that the government is trying to control how much energy households use, and that smart meters are a form of digital slavery. In reality, the government is not collecting or controlling the data. Households still have full control over their own data and it can only be used for billing purposes. The article also encourages people to refuse smart meters and to have them removed if they are already installed."
summary3_3 = "This article is an example of misinformation as it presents false information in order to create fear and paranoia. It suggests that the government is collecting and storing citizens' data with sinister motives, and that they are trying to control how much energy households use, when in reality smart meters are simply a more efficient and cost-effective way to monitor energy usage. Furthermore, citizens have the right to refuse smart meters and can request to have them removed if they have already been installed."










